language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
sudo: false
install:
    - pip install -U pip setuptools
    - pip install -U zope.testrunner
    - pip install -U -e .[test]
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
